In [1]:
from collections import defaultdict
from collections import Counter
from tqdm import tqdm
import pandas as pd
import numpy as np
import os

In [2]:
root = "/home/acomajuncosa/Documents_GPU/mtb-targeted-protein-degradation"

In [3]:
def get_splits(path):
    splits = os.listdir(path)
    return [i.replace(".csv", "") for i in sorted(splits)]

def get_pockets():
    df = pd.read_csv("/home/acomajuncosa/Documents_GPU/mtb-targeted-protein-degradation/processed/pocket_detection_data.csv")
    pockets = [f"{i.replace('.pdb', '')}_pocket_{j}" for i, j in zip(df['File name'], df['Pocket number'])]
    return sorted(pockets)

In [4]:
# Get splits (994)
SPLITS = get_splits(os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", 'A_proteins'))

# Get pockets (276)
POCKETS = get_pockets()

In [5]:
A_pockets = pd.read_csv(os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", "A_pockets.csv"))
B_pockets = pd.read_csv(os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", "B_pockets.csv"))
A_proteins = pd.read_csv(os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", "A_proteins.csv"))
B_proteins = pd.read_csv(os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", "B_proteins.csv"))

# Check that all pockets have same number of cpds associated
assert set(Counter(B_pockets['pocket']).values()) == set([1000])
assert set(Counter(B_proteins['pocket']).values()) == set([13000])

# Drop pocket column
B_pockets = B_pockets.drop(columns=['pocket'])
B_proteins = B_proteins.drop(columns=['pocket'])

# Include label
A_pockets['label'] = "A_pockets" 
B_pockets['label'] = "B_pockets" 
A_proteins['label'] = "A_proteins" 
B_proteins['label'] = "B_proteins"

# Merge all, sort and drop duplicates
COMPOUNDS = pd.concat([A_pockets, B_pockets, A_proteins, B_proteins]).sort_values(by=['split', 'index']).drop_duplicates(subset=['split', 'index']).reset_index(drop=True)

In [7]:
print(len(A_pockets) + len(B_pockets) + len(A_proteins) + len(B_proteins))
print(len(COMPOUNDS))
print((len(A_pockets) + len(B_pockets) + len(A_proteins) + len(B_proteins)) - len(COMPOUNDS))

1049000
1032646
16354

In [8]:
PATH_TO_SPLITS = os.path.join(root, "tmp")
PATH_TO_OUTPUT = os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", "selected_compounds")
os.makedirs(PATH_TO_OUTPUT, exist_ok=True)

In [9]:
ANNOTATED_COMPOUNDS = []

for split in tqdm(SPLITS[:100]):

    # Identify subset
    df = COMPOUNDS[COMPOUNDS['split'] == split].reset_index(drop=True)
    inds = df['index'].to_numpy()

    # Load split info
    smiles_ids = pd.read_csv(os.path.join(PATH_TO_SPLITS, f"{split}_SMILES_IDs.tsv.zip"), sep='\t')
    smiles_ids = smiles_ids.iloc[inds].reset_index()
    assert (smiles_ids['index'] == df['index']).all

    # Concatanate
    df = pd.concat([df, smiles_ids], axis=1)

    # Save
    df.to_csv(os.path.join(PATH_TO_OUTPUT, f"{split}.csv"), index=False)

100%|██████████| 100/100 [10:48<00:00,  6.48s/it]

In [10]:
def get_splits(path):
    splits = os.listdir(path)
    return [i.replace(".csv", "") for i in sorted(splits)]

def get_pockets():
    df = pd.read_csv("/home/acomajuncosa/Documents_GPU/mtb-targeted-protein-degradation/processed/pocket_detection_data.csv")
    pockets = [f"{i.replace('.pdb', '')}_pocket_{j}" for i, j in zip(df['File name'], df['Pocket number'])]
    return sorted(pockets)

In [11]:
PATH_TO_SELECTED_COMPOUNDS = os.path.join(root, "processed", "unidock_REAL_docking", "inference_10B", "selected_compounds")

In [41]:
df = []
for split in SPLITS:
    try:
        df_ = pd.read_csv(os.path.join(os.path.join(PATH_TO_OUTPUT, f"{split}.csv")))
        df.append(df_)
    except:
        pass
df = pd.concat(df, ignore_index=True)
rng = np.random.default_rng(42)
df["rd"] = rng.random(len(df))

CUSTOM_ORDER = ['A_proteins', 'A_pockets', 'B_proteins', 'B_pockets']
df["label"] = pd.Categorical(df["label"], categories=CUSTOM_ORDER, ordered=True)
df = df.sort_values(["label", "rd"], ascending=[True, True], kind="stable").reset_index(drop=True)

In [59]:
MAX_SYNTHON = 10
SYNTHON_COUNTS = defaultdict(int)
KEEP = []

for id_ in tqdm(df['id']):

    if id_.startswith("m_") == False and id_.startswith("s_") == False:
        raise TypeError("ID not starting with m nor s. Please revise")
    
    
    synthons = id_.split("____")[1:]
    keep = True
    tmp_dict = defaultdict(int)

    # tmp dict with synthons
    for synthon in synthons:
        tmp_dict[synthon] += 1

    # check valid compound
    for synthon in synthons:
        if SYNTHON_COUNTS[synthon] + tmp_dict[synthon] <= MAX_SYNTHON:
            pass
        else:
            keep = False
            break

    # add compound if valid
    if keep == True:
        KEEP.append(True)
        for synthon in synthons:
            SYNTHON_COUNTS[synthon] += 1
        
    else:
        KEEP.append(False)
        

df['keep'] = KEEP
d = Counter(KEEP)
print(round(100 * d[True] / (d[True] + d[False]), 2), "%")

100%|██████████| 113989/113989 [00:00<00:00, 906821.71it/s]

72.45 %

In [60]:
df

,split,index,n_targets,label,index.1,smiles,id,rd,keep
0,Enamine_REAL_LeadLike_008,4051326,21.0,A_proteins,4051326,FC1=C(C2=NC(C3CNCCO3)=NO2)SC=C1,m_271362____30583064____18521434,0.000013,True
1,Enamine_REAL_LeadLike_087,6127269,21.0,A_proteins,6127269,CC1=CNC(C(=O)NC2CN(C(=O)C3CNC(=O)N3)C2)=C1,m_275592____17554698____14140274____19055260,0.000056,True
2,Enamine_REAL_LeadLike_046,9127720,21.0,A_proteins,9127720,O=C(NCC1CSC1)C(=O)N1CCCC2=CC=CC=C21,s_2718____29034160____1019008,0.000057,True
3,Enamine_REAL_LeadLike_076,1487545,21.0,A_proteins,1487545,O=C(NC1=CN2N=CC=C2N=C1)C1=CC=C2NCCC2=C1,s_240690____13618256____9018314,0.000107,True
4,Enamine_REAL_LeadLike_027,7326378,21.0,A_proteins,7326378,CC1=NC=CC=C1NC(=O)C1=CC2=C(CNCC2)N1,s_240690____7399710____20276634,0.000152,True
...,...,...,...,...,...,...,...,...,...
113984,Enamine_REAL_LeadLike_044,9313705,50.0,B_pockets,9313705,C=C1CC2(C1)CN(C(=O)NC1=CN=C3NN=CC3=C1)C2,s_2430____15475208____26850320,0.999891,True
113985,Enamine_REAL_LeadLike_021,632022,50.0,B_pockets,632022,O=C(NNC1=CC(I)=CC=N1)C1=CN=C2SCCN12,s_22____14476978____13456062,0.999910,True
113986,Enamine_REAL_LeadLike_063,7092259,50.0,B_pockets,7092259,CC1=CC(F)=NC=C1NC(=O)C1=C2NC(O)=NC2=CN=C1,s_22____20075852____16803900,0.999915,True
113987,Enamine_REAL_LeadLike_088,8496329,50.0,B_pockets,8496329,O=C(CCC1=CN2N=NN=C2N=C1)OCC1COC(=O)N1,s_276436____14082488____31174282,0.999935,False
113988,Enamine_REAL_LeadLike_039,3755042,50.0,B_pockets,3755042,O=C(NCC1=COC=C1Br)C1=CC2=CC(F)=CC=C2N1,s_22____29301540____508510,0.999994,True

In [64]:
df[df['id'].str.contains("23521810")][:50]

,split,index,n_targets,label,index.1,smiles,id,rd,keep
6,Enamine_REAL_LeadLike_053,8627425,21.0,A_proteins,8627425,CC=CC(=O)N1CC=CC1C(=O)N1CCCC(O)CC1,m_274552____23521810____13186034____15986190,0.000160,True
877,Enamine_REAL_LeadLike_084,9589963,21.0,A_proteins,9589963,O=C(NC1=CC=C(O)C=C1)C1C=CCN1C(=O)C1CCO1,m_274552____23521810____24995232____15985840,0.033208,True
889,Enamine_REAL_LeadLike_084,9538074,21.0,A_proteins,9538074,NC(=O)C(=O)N1CC=CC1C(=O)NC1COCCC1(F)F,m_274552____23521810____15973642____15980482,0.033683,True
954,Enamine_REAL_LeadLike_053,8642655,21.0,A_proteins,8642655,CC1(O)CN(C(=O)C2C=CCN2C(=O)C2=NOC=C2)C1,m_274552____23521810____15958068____13454072,0.035462,True
1492,Enamine_REAL_LeadLike_084,9414478,21.0,A_proteins,9414478,O=C(NCC1=COC=N1)C1C=CCN1C(=O)C1CC=CC1,m_274552____23521810____12398572____13454210,0.055504,True
1952,Enamine_REAL_LeadLike_053,8657994,21.0,A_proteins,8657994,O=C(C1C=CCN1C(=O)C1=C(Cl)CC1)N1CC(CF)C1,m_274552____23521810____15968732____15986982,0.073293,True
2108,Enamine_REAL_LeadLike_084,9560735,21.0,A_proteins,9560735,[N-]=[N+]=NCCCC(=O)N1CC=CC1C(=O)N1CC=CCO1,m_274552____23521810____24976466____15975722,0.078416,True
2253,Enamine_REAL_LeadLike_053,8629868,21.0,A_proteins,8629868,[N-]=[N+]=NCC(=O)N1CC=CC1C(=O)NCC1=NN=CN1,m_274552____23521810____13730534____15979422,0.083175,True
2486,Enamine_REAL_LeadLike_084,9570803,21.0,A_proteins,9570803,CC=C1CN(C(=O)C2C=CCN2C(=O)[C@H]2CC=CCC2)C1,m_274552____23521810____24981984____25038678,0.092701,True
3256,Enamine_REAL_LeadLike_053,8628795,21.0,A_proteins,8628795,NC(=O)CNC(=O)C1C=CCN1C(=O)[C@@H]1COC(=O)N1,m_274552____23521810____13454578____15976290,0.122115,True
5426,Enamine_REAL_LeadLike_053,8628357,21.0,A_proteins,8628357,O=C(NC1CC=CC1)C1C=CCN1C(=O)C1CCOC1,m_274552____23521810____13186080____13454116,0.203761,False
5645,Enamine_REAL_LeadLike_084,9476850,21.0,A_proteins,9476850,CC1=NNC(=O)C(C(=O)N2CC=CC2C(=O)NC2CC2)=C1,m_274552____23521810____15956010____15982404,0.211593,False
5736,Enamine_REAL_LeadLike_084,9453535,21.0,A_proteins,9453535,O=C(C1=CC=NS1)N1CC=CC1C(=O)N1C2CCC1CC2,m_274552____23521810____13729616____15985764,0.214731,False
5750,Enamine_REAL_LeadLike_053,8696842,21.0,A_proteins,8696842,CCC(=O)N1CC=CC1C(=O)NC1=CC(C)=CC(O)=C1,m_274552____23521810____25005074____13453850,0.215115,False
5810,Enamine_REAL_LeadLike_084,9602502,21.0,A_proteins,9602502,O=C(C1C=CCN1C(=O)CC1CC2(CC2)C1)N1CCCO1,m_274552____23521810____24998868____15987966,0.217177,False
6685,Enamine_REAL_LeadLike_053,8691117,21.0,A_proteins,8691117,CC=CC(=O)N1CC=CC1C(=O)N1CC(O)(CCO)C1,m_274552____23521810____25000212____15986190,0.250117,False
7059,Enamine_REAL_LeadLike_084,9625581,21.0,A_proteins,9625581,O=C(NC1=CN=C(F)N=C1)C1C=CCN1C(=O)C1CSC1,m_274552____23521810____25011312____15981630,0.263328,False
7455,Enamine_REAL_LeadLike_084,9586218,21.0,A_proteins,9586218,O=C(N[C@H]1CCOC1)C1C=CCN1C(=O)C1=CC=CC=C1,m_274552____23521810____24993448____13453894,0.276751,False
7592,Enamine_REAL_LeadLike_084,9415126,21.0,A_proteins,9415126,O=C(C1C=CCN1C(=O)CC1CC2(CC2)C1)N1CC=CC1,m_274552____23521810____13184720____15987966,0.282113,False
8003,Enamine_REAL_LeadLike_053,8673681,21.0,A_proteins,8673681,O=C(N[C@H]1C[C@@H](F)C1)C1C=CCN1C(=O)C1=CSC=N1,m_274552____23521810____24978518____13454150,0.298107,False
8511,Enamine_REAL_LeadLike_084,9447438,21.0,A_proteins,9447438,O=C(NCC(Cl)Cl)C1C=CCN1C(=O)C1=CC=CC=C1O,m_274552____23521810____13185980____13454012,0.318590,False
8693,Enamine_REAL_LeadLike_084,9498563,21.0,A_proteins,9498563,O=C(C1C=CCN1C(=O)C1=CC=CO1)N1CCC[C@@H](O)C1,m_274552____23521810____15961432____13453882,0.326787,False
8842,Enamine_REAL_LeadLike_084,9587079,21.0,A_proteins,9587079,O=C(C1C=CCN1C(=O)C1CC=CC1)N1CC2CC1CO2,m_274552____23521810____24994046____13454210,0.332354,False
8891,Enamine_REAL_LeadLike_053,8651071,21.0,A_proteins,8651071,C#CC1(NC(=O)C2C=CCN2C(=O)C2CS(=O)C2)CC1,m_274552____23521810____15964064____25032204,0.334155,False
8949,Enamine_REAL_LeadLike_053,8609712,21.0,A_proteins,8609712,C#CCN(C)C(=O)C1C=CCN1C(=O)C1=C(C)C=CN1,m_274552____23521810____13184740____13454432,0.336188,False
9806,Enamine_REAL_LeadLike_053,8675194,21.0,A_proteins,8675194,O=C(NC1=CSN=C1)C1C=CCN1C(=O)C#CC1CC1,m_274552____23521810____24980906____13454492,0.367672,False
10779,Enamine_REAL_LeadLike_084,9501053,21.0,A_proteins,9501053,O=C(NC1CC2CC2C1)C1C=CCN1C(=O)C1=CC=CN1,m_274552____23521810____15962128____13453972,0.405013,False
11249,Enamine_REAL_LeadLike_053,8678381,21.0,A_proteins,8678381,C=CC1CCN1C(=O)C1C=CCN1C(=O)C1=NC=CN1,m_274552____23521810____24986652____15979292,0.422669,False
11323,Enamine_REAL_LeadLike_084,9586368,21.0,A_proteins,9586368,O=C(N[C@H]1CCOC1)C1C=CCN1C(=O)C1=CC=NN=C1,m_274552____23521810____24993448____15983816,0.425446,False
11456,Enamine_REAL_LeadLike_084,9528788,21.0,A_proteins,9528788,C[C@H]1C[C@H]1C(=O)N1CC=CC1C(=O)N1CC2(CCCO2)C1,m_274552____23521810____15970542____25036090,0.429834,False
12570,Enamine_REAL_LeadLike_053,8697830,21.0,A_proteins,8697830,O=C1NC=NC=C1NC(=O)C1C=CCN1C(=O)C(F)F,m_274552____23521810____25005974____13453854,0.472897,False
13146,Enamine_REAL_LeadLike_084,9599402,21.0,A_proteins,9599402,CC1=NOC=C1NC(=O)C1C=CCN1C(=O)C1SCCS1,m_274552____23521810____24998178____15979686,0.494339,False
13571,Enamine_REAL_LeadLike_084,9545551,21.0,A_proteins,9545551,O=C(C1C=CCN1C(=O)C1=C(Cl)C=NN1)N1CCC1CF,m_274552____23521810____24966324____15975516,0.510026,False
14013,Enamine_REAL_LeadLike_084,9578997,21.0,A_proteins,9578997,C=C1CC(C)(NC(=O)C2C=CCN2C(=O)[C@@H]2CCCO2)C1,m_274552____23521810____24988122____13454328,0.527098,False
14032,Enamine_REAL_LeadLike_053,8650961,21.0,A_proteins,8650961,C#CC1(NC(=O)C2C=CCN2C(=O)C2=NOC=C2)CC1,m_274552____23521810____15964064____13454072,0.527780,False
14593,Enamine_REAL_LeadLike_053,8656916,21.0,A_proteins,8656916,C[C@@H]1CCCN1C(=O)C1C=CCN1C(=O)C1=CSC=N1,m_274552____23521810____15968368____13454150,0.549351,False
15609,Enamine_REAL_LeadLike_084,9543298,21.0,A_proteins,9543298,CC1(F)CN(C(=O)C2C=CCN2C(=O)C2=NNC(N)=N2)C1,m_274552____23521810____24965382____15976948,0.588478,False
16540,Enamine_REAL_LeadLike_084,9451109,21.0,A_proteins,9451109,O=C1CC(C(=O)N2CC=CC2C(=O)NC2CC=CC2)CN1,m_274552____23521810____13186080____15986522,0.621929,False
17457,Enamine_REAL_LeadLike_053,8614243,21.0,A_proteins,8614243,CCCNC(=O)C1C=CCN1C(=O)C1=CC=CC(=O)N1,m_274552____23521810____13184882____13454236,0.658049,False
19142,Enamine_REAL_LeadLike_084,9583799,21.0,A_proteins,9583799,C[C@H]1COC[C@H]1NC(=O)C1C=CCN1C(=O)C1=NNC=C1 |...,m_274552____23521810____24992302____13454032,0.720322,False
19732,Enamine_REAL_LeadLike_084,9557206,21.0,A_proteins,9557206,C=CC1CN(C(=O)C2C=CCN2C(=O)C2=C(Cl)C=NN2)C1,m_274552____23521810____24973864____15975516,0.742015,False
20354,Enamine_REAL_LeadLike_053,8609081,21.0,A_proteins,8609081,CC1=CC=C(C(=O)N2CC=CC2C(=O)N2CC=CC2)S1,m_274552____23521810____13184720____13453888,0.765092,False
21133,Enamine_REAL_LeadLike_084,9618905,21.0,A_proteins,9618905,CN1N=CC(C(=O)N2CC=CC2C(=O)NC2=CSC=C2)=N1,m_274552____23521810____25005948____15986568,0.793921,False
21753,Enamine_REAL_LeadLike_053,8609336,21.0,A_proteins,8609336,CC1=NOC(C(=O)N2CC=CC2C(=O)N2CC=CC2)C1,m_274552____23521810____13184720____15985780,0.816831,False
21813,Enamine_REAL_LeadLike_084,9490378,21.0,A_proteins,9490378,CC(=O)C1=CC=C(C(=O)N2CC=CC2C(=O)N2CCC2)O1,m_274552____23521810____15959006____15975694,0.819174,False
24127,Enamine_REAL_LeadLike_084,9461596,21.0,A_proteins,9461596,O=C(NC1CC(F)(F)C1)C1C=CCN1C(=O)C1=COCC1,m_274552____23521810____13734246____15984832,0.909073,False
24260,Enamine_REAL_LeadLike_084,9615175,21.0,A_proteins,9615175,CC1=NOC=C1C(=O)N1CC=CC1C(=O)NN1C=CC=N1,m_274552____23521810____25004084____15978020,0.914136,False
25223,Enamine_REAL_LeadLike_053,8690965,21.0,A_proteins,8690965,CC1=CCN(C(=O)C2C=CCN2C(=O)C(C)=C2CC2)C1,m_274552____23521810____25000202____15974454,0.952371,False
25411,Enamine_REAL_LeadLike_084,9524238,21.0,A_proteins,9524238,O=C(NC1C=CCC1)C1C=CCN1C(=O)CC1=CNC=C1,m_274552____23521810____15968808____15980518,0.959879,False
26047,Enamine_REAL_LeadLike_084,9573467,21.0,A_proteins,9573467,CC1=C(C(=O)N2CC=CC2C(=O)N[C@H]2C[C@H](O)[C@H]2...,m_274552____23521810____24983834____25056654,0.982741,False

In [62]:
SYNTHON_COUNTS

defaultdict(int,
            {'30583064': 10,
             '18521434': 1,
             '17554698': 10,
             '14140274': 4,
             '19055260': 1,
             '29034160': 3,
             '1019008': 5,
             '13618256': 1,
             '9018314': 5,
             '7399710': 2,
             '20276634': 10,
             '903382': 1,
             '13259644': 8,
             '23521810': 10,
             '13186034': 1,
             '15986190': 10,
             '21917024': 1,
             '22359982': 10,
             '21950962': 3,
             '23821668': 1,
             '14587542': 4,
             '29025332': 2,
             '29066894': 2,
             '29315392': 1,
             '5635096': 5,
             '23075216': 4,
             '26278352': 4,
             '8805270': 10,
             '7404658': 2,
             '14484024': 6,
             '16783582': 2,
             '15735482': 2,
             '14780374': 1,
             '21554958': 2,
             '13970086': 5,
             '14313888': 5,
             '17782846': 10,
             '17026298': 4,
             '25121626': 4,
             '15759294': 4,
             '25447876': 10,
             '8125638': 4,
             '29647964': 10,
             '26468100': 1,
             '26580336': 1,
             '23414932': 5,
             '24980052': 10,
             '15985840': 10,
             '12330814': 2,
             '13286614': 2,
             '22174468': 8,
             '22157592': 8,
             '9104820': 10,
             '22591238': 3,
             '9104818': 10,
             '13263562': 5,
             '23522394': 10,
             '15969780': 10,
             '15986804': 1,
             '4557852': 10,
             '28905544': 1,
             '23414974': 10,
             '13454600': 10,
             '25037386': 4,
             '32255512': 6,
             '4903368': 6,
             '15479198': 6,
             '30503356': 2,
             '23522170': 10,
             '13733202': 3,
             '15984656': 10,
             '21890314': 4,
             '22003036': 8,
             '21945300': 4,
             '8740730': 2,
             '29517586': 1,
             '12107402': 1,
             '30755888': 1,
             '10125660': 1,
             '26876710': 5,
             '25819782': 7,
             '10389286': 3,
             '22169100': 6,
             '1880454': 3,
             '26983890': 2,
             '28841894': 2,
             '28741282': 1,
             '12354756': 3,
             '27423716': 3,
             '27219056': 1,
             '11829844': 3,
             '21743584': 5,
             '28245160': 1,
             '28798300': 6,
             '28245212': 4,
             '15480112': 5,
             '23519288': 10,
             '25014388': 1,
             '13453852': 10,
             '128741': 10,
             '22138900': 10,
             '25546426': 1,
             '3735144': 10,
             '8930780': 3,
             '681758': 10,
             '21897234': 2,
             '22360176': 10,
             '21965680': 10,
             '8728': 4,
             '6389516': 2,
             '7080836': 1,
             '8987398': 10,
             '23832698': 10,
             '23878118': 1,
             '28265242': 10,
             '28620786': 1,
             '19116862': 10,
             '28806072': 1,
             '10638202': 1,
             '12120984': 10,
             '9867826': 1,
             '22390692': 4,
             '20331088': 1,
             '21466814': 6,
             '28735810': 3,
             '12014594': 2,
             '26108424': 1,
             '26271496': 2,
             '25797926': 10,
             '24987740': 1,
             '15986400': 10,
             '15967036': 10,
             '13454362': 5,
             '31149522': 1,
             '11993890': 4,
             '28780458': 1,
             '25412738': 6,
             '27712492': 1,
             '27421782': 10,
             '53393': 7,
             '26273758': 5,
             '11686174': 5,
             '20854886': 7,
             '11945846': 3,
             '30721434': 2,
             '22545148': 3,
             '22136046': 10,
             '25974644': 2,
             '483184': 1,
             '51613': 2,
             '18235136': 4,
             '101968': 2,
             '27417562': 9,
             '21780484': 1,
             '22607960': 3,
             '27470672': 1,
             '17777020': 1,
             '17809348': 10,
             '14085144': 6,
             '14089840': 1,
             '31161276': 4,
             '138877': 10,
             '30208450': 1,
             '30194532': 10,
             '15141334': 4,
             '17827792': 2,
             '26473272': 1,
             '26542990': 1,
             '19730664': 1,
             '28761786': 4,
             '12102822': 6,
             '14261486': 1,
             '25841514': 4,
             '22022146': 4,
             '16922796': 2,
             '15150474': 1,
             '14900006': 10,
             '24998190': 2,
             '13454210': 10,
             '10267554': 3,
             '29644544': 4,
             '23414938': 10,
             '24998868': 10,
             '13454300': 3,
             '24330896': 2,
             '24221990': 3,
             '16804848': 3,
             '20042618': 1,
             '22399112': 2,
             '7471848': 9,
             '7425610': 3,
             '13570734': 6,
             '25843886': 2,
             '18358120': 8,
             '21970624': 10,
             '21212502': 6,
             '7115732': 1,
             '22170976': 8,
             '18716084': 1,
             '15142776': 1,
             '10264516': 10,
             '7288880': 3,
             '14591744': 3,
             '17026374': 7,
             '13941860': 3,
             '293596': 3,
             '22009590': 6,
             '479536': 1,
             '26093208': 4,
             '21434996': 2,
             '17751246': 3,
             '25583240': 3,
             '13753936': 10,
             '7348260': 1,
             '16915814': 7,
             '22061750': 6,
             '22112270': 1,
             '21899590': 5,
             '26669682': 10,
             '21970396': 1,
             '28573152': 3,
             '156106': 3,
             '13761716': 4,
             '11243716': 6,
             '28267232': 4,
             '21747826': 3,
             '9963536': 3,
             '28486762': 2,
             '15587518': 10,
             '28552010': 1,
             '28778948': 1,
             '12198050': 8,
             '10267186': 1,
             '16711396': 10,
             '58839': 5,
             '26074672': 10,
             '3191148': 1,
             '14772906': 2,
             '10330370': 10,
             '16784238': 2,
             '27267678': 3,
             '27220036': 1,
             '22081008': 7,
             '31948450': 1,
             '25289478': 2,
             '7548812': 9,
             '26256870': 10,
             '28886564': 1,
             '15607620': 10,
             '28543988': 4,
             '11471850': 3,
             '28759852': 1,
             '26478182': 2,
             '26574280': 1,
             '16655702': 4,
             '13205822': 4,
             '29798982': 3,
             '14915852': 10,
             '9425916': 1,
             '19891998': 2,
             '23858934': 1,
             '22499174': 1,
             '23414912': 10,
             '24969910': 1,
             '15975436': 7,
             '23414930': 10,
             '25011162': 4,
             '13453966': 6,
             '28665282': 10,
             '28625304': 3,
             '29184832': 6,
             '18329128': 4,
             '10427786': 7,
             '18759752': 7,
             '23109362': 1,
             '23179094': 10,
             '30377998': 4,
             '7368654': 6,
             '13465792': 10,
             '24859240': 1,
             '29561326': 6,
             '10227364': 1,
             '28267052': 5,
             '28551170': 4,
             '12427336': 10,
             '28763936': 1,
             '27472790': 1,
             '31840472': 2,
             '18040818': 1,
             '17996550': 10,
             '4147618': 3,
             '29064822': 2,
             '7347440': 4,
             '27703768': 1,
             '28244982': 10,
             '28796908': 1,
             '6894010': 4,
             '28380758': 10,
             '22172866': 3,
             '20888984': 3,
             '15735146': 6,
             '31160268': 1,
             '10901824': 1,
             '26295770': 5,
             '8370778': 3,
             '22448800': 10,
             '25841748': 5,
             '7344292': 3,
             '18757970': 10,
             '23463946': 2,
             '15977236': 4,
             '13421042': 5,
             '6483052': 5,
             '26978364': 4,
             '25804620': 2,
             '11986924': 3,
             '6957986': 10,
             '24038310': 1,
             '19130330': 5,
             '21853604': 8,
             '19994910': 3,
             '15409756': 10,
             '21747098': 10,
             '28245214': 10,
             '28795148': 2,
             '22071330': 3,
             '22110144': 2,
             '12890326': 2,
             '53711': 10,
             '23841014': 2,
             '17514408': 1,
             '13766120': 1,
             '31921976': 10,
             '18379538': 3,
             '14105378': 2,
             '17833278': 10,
             '16543460': 2,
             '16812498': 5,
             '16603800': 10,
             '13037876': 2,
             '8861288': 3,
             '21912890': 4,
             '23157406': 10,
             '21938976': 1,
             '22171944': 10,
             '8752032': 8,
             '8935786': 1,
             '30562080': 4,
             '503066': 1,
             '8281524': 1,
             '20500936': 5,
             '2991100': 3,
             '30147060': 10,
             '5343024': 3,
             '4557776': 10,
             '19663506': 2,
             '6585624': 3,
             '14062652': 7,
             '16945828': 3,
             '28774720': 2,
             '14082876': 5,
             '14104266': 4,
             '22076512': 1,
             '22126464': 3,
             '29537318': 4,
             '27382770': 3,
             '11952206': 1,
             '29375394': 7,
             '14079434': 4,
             '14091290': 2,
             '12906938': 1,
             '27485524': 3,
             '15355956': 2,
             '21417596': 4,
             '23280492': 1,
             '11735354': 2,
             '22166376': 10,
             '147672': 1,
             '30626134': 1,
             '27060970': 1,
             '7044544': 2,
             '2163424': 1,
             '19647250': 10,
             '24997790': 1,
             '25023684': 4,
             '10267104': 4,
             '23982584': 3,
             '28739636': 3,
             '19897564': 2,
             '12344494': 2,
             '3025750': 8,
             '14269856': 10,
             '14706516': 1,
             '22867922': 2,
             '31570078': 10,
             '393538': 1,
             '12053808': 9,
             '22449866': 5,
             '14916576': 7,
             '7401148': 1,
             '22877472': 8,
             '22865020': 4,
             '12807966': 10,
             '26644376': 1,
             '9405756': 10,
             '51634': 8,
             '22009054': 5,
             '21037616': 4,
             '20020248': 4,
             '30625006': 5,
             '21040548': 5,
             '28251738': 1,
             '26269798': 5,
             '6475378': 8,
             '26690318': 1,
             '25460132': 1,
             '20704220': 3,
             '24709222': 4,
             '11408426': 3,
             '3695596': 5,
             '18058540': 1,
             '18685136': 2,
             '17667660': 4,
             '10464170': 7,
             '24596432': 9,
             '22526426': 2,
             '16981144': 5,
             '18327284': 4,
             '24721410': 8,
             '23794376': 3,
             '8853856': 10,
             '21574418': 2,
             '17626966': 8,
             '11830172': 2,
             '28616778': 1,
             '23840864': 2,
             '21211400': 2,
             '15234926': 1,
             '12656228': 1,
             '24645956': 3,
             '22076514': 1,
             '22122650': 2,
             '13895942': 5,
             '105579': 7,
             '14114750': 10,
             '13186906': 3,
             '19067188': 5,
             '14114646': 10,
             '14139568': 6,
             '14133140': 6,
             '23522454': 10,
             '24981282': 10,
             '15985780': 2,
             '23172326': 10,
             '18687320': 2,
             '22595162': 10,
             '25661782': 1,
             '12546636': 10,
             '22137710': 4,
             '25559900': 3,
             '262944': 10,
             '27319710': 1,
             '10210452': 6,
             '26076202': 1,
             '19726434': 3,
             '25960052': 1,
             '26093100': 4,
             '24161092': 2,
             '12112422': 3,
             '19980170': 1,
             '9111854': 7,
             '52575': 1,
             '54046': 8,
             '14325654': 1,
             '30631236': 2,
             '27707358': 1,
             '23986244': 5,
             '7564470': 5,
             '14944868': 1,
             '22060542': 3,
             '31927038': 1,
             '2234584': 2,
             '28892346': 2,
             '9359274': 1,
             '8990144': 3,
             '14787342': 1,
             '923740': 8,
             '21916304': 1,
             '31478396': 10,
             '21972758': 1,
             '22166404': 10,
             '26275804': 5,
             '12059656': 3,
             '25393986': 7,
             '29642262': 10,
             '137140': 1,
             '24322132': 1,
             '24222204': 6,
             '53181': 1,
             '26251770': 10,
             '19177002': 1,
             '23931898': 6,
             '8935878': 10,
             '8936672': 1,
             '17902542': 1,
             '21001910': 10,
             '10176472': 10,
             '8686660': 6,
             '24303544': 1,
             '24203084': 10,
             '9780436': 5,
             '12907104': 9,
             '23172110': 10,
             '31170808': 1,
             '10145238': 10,
             '24861390': 2,
             '13186972': 1,
             '21837454': 7,
             '10176488': 7,
             '26872166': 8,
             '22166966': 5,
             '22022420': 5,
             '11735020': 6,
             '13817768': 4,
             '10331830': 1,
             '20885192': 4,
             '22180202': 10,
             '21547164': 5,
             '27079336': 1,
             '27391522': 8,
             '14577704': 10,
             '29223260': 1,
             '6103838': 8,
             '26254834': 2,
             '1111910': 2,
             '6725234': 8,
             '7143514': 1,
             '14916220': 10,
             '11771162': 10,
             '28621984': 1,
             '6078802': 1,
             '11243982': 7,
             '25800378': 3,
             '16924434': 2,
             '10432782': 5,
             '25878398': 10,
             '25889726': 1,
             '16786840': 10,
             '13219556': 1,
             '25565020': 1,
             '10973754': 8,
             '18613058': 1,
             '15985894': 6,
             '28717342': 3,
             '27359490': 1,
             '22174844': 6,
             '25921640': 10,
             '30857282': 1,
             '30641508': 1,
             '20075254': 1,
             '16439236': 3,
             '20329048': 4,
             '26276544': 10,
             '16635700': 1,
             '9779924': 7,
             '11758778': 2,
             '7548800': 2,
             '18341564': 1,
             '22788830': 3,
             '7347336': 5,
             '24782290': 1,
             '25841156': 4,
             '25986796': 8,
             '26643974': 4,
             '2366858': 9,
             '17063694': 10,
             '23069188': 1,
             '21897300': 9,
             '21964434': 5,
             '24195844': 10,
             '15840566': 4,
             '15856878': 3,
             '24977446': 1,
             '15985764': 9,
             '28615980': 1,
             '14726222': 6,
             '14040176': 5,
             '14114670': 8,
             '14141778': 4,
             '15856668': 10,
             '25838722': 8,
             '14916244': 2,
             '25842212': 5,
             '26270462': 10,
             '22066898': 10,
             '22053278': 1,
             '22523978': 3,
             '11759392': 3,
             '22434514': 4,
             '17033650': 1,
             '19732554': 9,
             '20994730': 1,
             '11686178': 4,
             '8627144': 10,
             '20019842': 10,
             '13187320': 10,
             '15857492': 5,
             '22406068': 2,
             '9142584': 2,
             '28264002': 10,
             '21748042': 1,
             '7345842': 4,
             '26682446': 1,
             '23848698': 10,
             '23881256': 3,
             '26294972': 3,
             '23466542': 3,
             '25493488': 2,
             '14868424': 10,
             '29909122': 2,
             '23828518': 5,
             '11975892': 2,
             '18613004': 10,
             '15959006': 10,
             '15979416': 1,
             '17762038': 2,
             '14772380': 10,
             '12052812': 3,
             '25592450': 2,
             '12129490': 1,
             '6740000': 9,
             '29186570': 4,
             '14105986': 5,
             '17523338': 1,
             '22384728': 7,
             '21556926': 2,
             '25121600': 4,
             '10660': 10,
             '29670656': 2,
             '29302540': 1,
             '12890442': 10,
             '10430634': 7,
             '24027988': 2,
             '19619516': 2,
             '28567380': 4,
             '29642356': 1,
             '30379970': 10,
             '13225796': 2,
             '9598350': 3,
             '8936280': 3,
             '17697738': 1,
             '21246482': 1,
             '4994096': 3,
             '9297776': 5,
             '24715482': 1,
             '14075858': 3,
             '14089964': 1,
             '28889648': 8,
             '17068484': 7,
             '20993328': 1,
             '26092310': 6,
             '22172940': 10,
             '7143474': 6,
             '14780866': 2,
             '24750300': 4,
             '17693320': 3,
             '2306616': 6,
             '22186950': 1,
             '340092': 10,
             '24641908': 3,
             '13651884': 1,
             '10269288': 3,
             '13422300': 10,
             '154503': 3,
             '3392708': 2,
             '4914242': 2,
             '5073': 9,
             '7352986': 3,
             '19725284': 10,
             '17756900': 1,
             '9315790': 6,
             '10145160': 4,
             '28539826': 2,
             '26989032': 2,
             '9576144': 2,
             '20334650': 1,
             '15491962': 1,
             '24291728': 4,
             '24221504': 4,
             '26254262': 2,
             '27068806': 10,
             '22077626': 1,
             '511594': 8,
             '24308540': 2,
             '24221614': 8,
             '22987718': 3,
             '3223074': 1,
             '12808258': 1,
             '25421446': 10,
             '605544': 6,
             '5128482': 10,
             '15970956': 1,
             '15988090': 1,
             '11375028': 1,
             '20276638': 1,
             '24202606': 5,
             '25922996': 10,
             '28246340': 4,
             '4595290': 10,
             '13580176': 2,
             '21597402': 7,
             '14928206': 10,
             '12422130': 2,
             '23189748': 1,